In [2]:
import torch

x = torch.randn(3, requires_grad= True)

print(x)

# This creates an operational graph that helps with backpropagation
y = x + 2
print(y)

z = y*y*2
z = z.mean()
print(z)

tensor([ 0.8660,  0.1976, -0.2199], requires_grad=True)
tensor([2.8660, 2.1976, 1.7801], grad_fn=<AddBackward0>)
tensor(10.8082, grad_fn=<MeanBackward0>)


In [3]:
# this will calculate the gradient of z wrt to tensor x dz/dx
# These gradeitns will be stores in x.grad()
z.backward()
# Since z here is a scalar value 
# We dont have to multiply it with a jakovian vector
# grad can be implicitly created for scalar values
print(x.grad)

tensor([3.8214, 2.9302, 2.3734])


In [4]:
# Here z is a vector not a scalar
z = y*y*2

v = torch.tensor([0.1,1.0,0.001], dtype= torch.float32)
z.backward(v)
print(x.grad)

tensor([ 4.9678, 11.7207,  2.3806])


In [6]:
# Prevent the tracking the gradient of tensors that we dont want to find the gradient of

# this changes the inplace variable
x.requires_grad_(False)
print(x)
# this reutnrs a tensor detached from the operation graph tensor flow creates
y = x.detach()
print(y)

x = torch.ones(3)
with torch.no_grad():
    y = x + 2
    print(y)

tensor([ 0.8660,  0.1976, -0.2199])
tensor([ 0.8660,  0.1976, -0.2199])
tensor([3., 3., 3.])


In [12]:
weights = torch.ones(4 , requires_grad = True)

for epoch in range(2):
    model_output = (weights*3).sum() 
    print(model_output)
    model_output.backward()
    
    print(weights.grad)
# Here you can notice that the gradients are accumulating the weights.grad
# TO prevent that do the below

tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([6., 6., 6., 6.])


In [14]:
weights = torch.ones(4 , requires_grad = True)

for epoch in range(2):
    model_output = (weights*3).sum()
    
    model_output.backward()
    
    print(weights.grad)
    
    # This will clear the previous gradients
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
