In [22]:
import torch 
import numpy as np

x = torch.empty(3)
print(x)

x = torch.empty(2,3)
print(x)

x = torch.empty(2,2,3)
print(x)

tensor([0., 0., 0.])
tensor([[8.2661e-10, 1.0073e-11, 6.6820e+22],
        [1.3592e+22, 3.3554e-06, 2.5207e-09]])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [7]:
x = torch.rand(2,2)
print(x)

tensor([[0.1001, 0.0468],
        [0.6296, 0.8723]])


In [8]:
x = torch.ones(2,2,dtype=torch.int)
print(x)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)


In [9]:
print(x.size())

torch.Size([2, 2])


In [10]:
x = torch.tensor([2,3,4])
print(x)

tensor([2, 3, 4])


In [11]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x, y)
z = x + y
print(z)
z = torch.add(z,y)
print(z)

tensor([[0.5557, 0.7550],
        [0.3886, 0.2396]]) tensor([[0.5491, 0.3589],
        [0.4443, 0.0423]])
tensor([[1.1047, 1.1140],
        [0.8329, 0.2819]])


In [12]:
y.add_(x)
# trailing underscore will do and in place operation
print(y)

tensor([[1.1047, 1.1140],
        [0.8329, 0.2819]])


In [13]:
z = x - y
z = torch.sub(x,y)
print(z)

z = torch.mul(x,y)
print(z)

z = torch.div(x,y)
print(z)

tensor([[-0.5491, -0.3589],
        [-0.4443, -0.0423]])
tensor([[0.6139, 0.8411],
        [0.3237, 0.0675]])
tensor([[0.5030, 0.6778],
        [0.4666, 0.8500]])


In [15]:
x  = torch.rand(5, 3)
print(x)
#print all columns of first row
print(x[1,:])

tensor([[0.6167, 0.1808, 0.4396],
        [0.5944, 0.0340, 0.7649],
        [0.4396, 0.3817, 0.2992],
        [0.5493, 0.3689, 0.8026],
        [0.1496, 0.8289, 0.0037]])
tensor([0.5944, 0.0340, 0.7649])


In [17]:
print(x[1,1])
print(x[1,1].item())

tensor(0.0340)
0.03404974937438965


In [19]:
x = torch.rand(4,4)
# makes the matrix into 1 dimensional vector
y = x.view(16)
print(y)

tensor([0.7710, 0.3317, 0.2779, 0.7248, 0.9734, 0.8695, 0.5878, 0.2347, 0.5775,
        0.7689, 0.9167, 0.0962, 0.1681, 0.2052, 0.7005, 0.9178])


In [21]:
x = torch.rand(4,4)
# if we do not know or want to specifiy one of the dimensions 
# pytorch will automatically determine that dimension
y = x.view(-1,8)
# this will now print 2, 8 dimensional tensor
print(y)

tensor([[0.5137, 0.6008, 0.6068, 0.8773, 0.5733, 0.5268, 0.6719, 0.0565],
        [0.8675, 0.5200, 0.7047, 0.4315, 0.6249, 0.6011, 0.2857, 0.4914]])


In [31]:
a = torch.ones(5)
b = a.numpy()
print(type(b))

a.add_(1)
# changes in a will also change b
print(b)

a = np.ones(5)
b = torch.from_numpy(a)
print(type(b))

<class 'numpy.ndarray'>
[2. 2. 2. 2. 2.]
<class 'torch.Tensor'>


In [35]:
# Moves the tensor to the GPU
device = torch.device('cuda')
x = torch.ones(5, device= device)
y = torch.ones(5, device= device)
z = x + y
# z.numpy() wont work because numpy cannot handle gpu tensors
z = z.to('cpu')

In [ ]:
# this specifies that pytorch will have to calculate the gradient of this tensor
x = torch.ones(5, requires_grad=True)