In [1]:
import torch
import torch.nn as nn

In [2]:
class Model(nn.Module):
    def __init__(self, n_input_features):
        super(Model, self).__init__()
        self.linear = nn.Linear(n_input_features, 1)
        
    def forward(x):
        x = self.linear(x)
        y = torch.sigmoid(x)
        return y

In [4]:
model = Model(n_input_features = 6)

In [ ]:
FILE = "model.pth"
torch.save(model, FILE)

In [9]:
# model must be created agin with parameters
model = torch.load(FILE)
model.eval()

for param in model.parameters():
    print(param)

Parameter containing:
tensor([[ 0.2444, -0.1012,  0.1034, -0.0449,  0.2428,  0.3505]],
       requires_grad=True)
Parameter containing:
tensor([0.1758], requires_grad=True)


In [10]:
# Preffered way
FILE = "model2.pth"
torch.save(model.state_dict(), FILE)

In [12]:
loaded_model = Model(n_input_features=6)
loaded_model.load_state_dict(torch.load(FILE))
loaded_model.eval()

for param in loaded_model.parameters():
    print(param)

Parameter containing:
tensor([[ 0.2444, -0.1012,  0.1034, -0.0449,  0.2428,  0.3505]],
       requires_grad=True)
Parameter containing:
tensor([0.1758], requires_grad=True)


In [5]:
model = Model(n_input_features = 6)

learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr= learning_rate)
print(optimizer.state_dict())

{'state': {}, 'param_groups': [{'lr': 0.01, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'differentiable': False, 'params': [0, 1]}]}


In [6]:
# saving a checkpoint during training
checkpoint = {
    "epoch": 90,
    "model_state": model.state_dict(),
    "optim_state": optimizer.state_dict()
}

torch.save(checkpoint, "checkpoint.pth")

In [11]:
loaded_checkpoint = torch.load("checkpoint.pth")
epoch = loaded_checkpoint["epoch"]

model = Model(n_input_features = 6)
optimizer = torch.optim.SGD(model.parameters(), lr=0)
optimizer.load_state_dict(loaded_checkpoint["optim_state"])
model.load_state_dict(loaded_checkpoint["model_state"])

<All keys matched successfully>

In [15]:
#To save on CPU and load on GPU
FILE = "model3.pth"
torch.save(model.state_dict(), FILE)

device = torch.device("cuda")
model = Model(n_input_features = 6)
model.load_state_dict(torch.load(FILE, map_location="cuda:0"))
model.to(device)

Model(
  (linear): Linear(in_features=6, out_features=1, bias=True)
)