In [2]:
import torch
import torch.nn as nn

In [3]:
# soft max
x = torch.tensor([2.0, 1.0, 0.1])
outputs = torch.softmax(x, dim = 0)
print(outputs)

tensor([0.6590, 0.2424, 0.0986])


In [16]:
# Corss Entropy
loss = nn.CrossEntropyLoss()

# this says that the expected output is class zero
Y = torch.tensor([0])
# N samples x N classes = 1x3
# Here class zero has the highest value 
Y_pred_good = torch.tensor([[2.0, 1.0, 0.1]])
# Here class zero has the lowest value
Y_pred_bad = torch.tensor([[0.5, 2.0, 0.3]])

l1 = loss(Y_pred_good, Y)
l2 = loss(Y_pred_bad, Y)

print(l1.item())
print(l2.item())

# Taking out the predictions
_, prediction1 = torch.max(Y_pred_good, 1)
_, prediction2 = torch.max(Y_pred_bad, 1)

print(prediction1, prediction2)

0.4170299470424652
1.840616226196289
tensor([0]) tensor([1])


In [18]:
# Similar to above
# this says that the expected output is class one
Y = torch.tensor([1])
# N samples x N classes = 1x3
# Here class one has the Lowest value 
Y_pred_bad = torch.tensor([[2.0, 1.0, 0.1]])
# Here class one has the highest value
Y_pred_good = torch.tensor([[0.5, 2.0, 0.3]])

l1 = loss(Y_pred_bad, Y)
l2 = loss(Y_pred_good, Y)

print(l1.item())
print(l2.item())

# Taking out the predictions
_, prediction1 = torch.max(Y_pred_bad, 1)
_, prediction2 = torch.max(Y_pred_good, 1)

print(prediction1, prediction2)

1.4170299768447876
0.34061628580093384
tensor([0]) tensor([1])


In [19]:
# In the above examples we can see that the labled tensor Y has only one class 
# but Ideally if there are 3 predictions then there should be 3 class in the labled tensor as well
# Corss Entropy
loss = nn.CrossEntropyLoss()

# this says that the expected outputs are class two, zero, one
Y = torch.tensor([2,0,1])
# N samples x N classes = 3x3
# Here class two zero has the highest value in first element 
# Class zero has the highest value in the second element 
# CLass one has the highest value in the third element
Y_pred_good = torch.tensor([[1.0, 0.1, 2.0], [2.0, 0.1, 1.0], [1.0, 2.0, 0.1]])
# Here class zero has the lowest value
Y_pred_bad = torch.tensor([[1.0, 2.0, 0.1], [1.0, 0.1, 2.0], [2.0, 1.0, 0.1]])

l1 = loss(Y_pred_good, Y)
l2 = loss(Y_pred_bad, Y)

print(l1.item())
print(l2.item())

# Taking out the predictions
_, prediction1 = torch.max(Y_pred_good, 1)
_, prediction2 = torch.max(Y_pred_bad, 1)

print(prediction1, prediction2)

0.4170299768447876
1.7170299291610718
tensor([2, 0, 1]) tensor([1, 2, 0])
